name: Run Tests On Postgres
on:
- push
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        env:
          POSTGRES_PASSWORD: postgres
        image: postgres:alpine
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - 5432:5432

    steps:
    - uses: actions/checkout@v2

    - name: Import schema
      run: psql -d postgresql://postgres@localhost/postgres -f schema.sql
      env:
        PGPASSWORD: postgres

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
          php-version: '8.1'
          extensions: pdo, pdo_pgsql
          tools: composer:v2
          coverage: none

    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --prefer-dist

    - name: Run PHPUnit
      env:
        CONNECTION_STRING: 'pgsql:host=localhost;dbname=postgres;user=postgres;password=postgres'
      run: ./vendor/bin/phpunit
